### ISSUE TITLE
Arduino as ESP-IDF component using this platform?

### ISSUE THREAD

**Issue by mairas** [pioarduino/platform-espressif32#22]
Hi,

Thanks for the great initiative.

I'm trying to figure out whether it is possible and/or how to use [Arduino as an ESP-IDF component](https://community.platformio.org/t/arduino-as-espif-component-in-platformio-solution-that-works/36542) using this platform. My naïve solution of just using the following `platformio.ini` config didn't seem to work (the build process is identical to regular PlatformIO Arduino):

```
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip
board = esp32dev
framework = arduino, espidf
```

**Comment by Jason2866** [comment]
See in examples how to do. It is working as exactly like this.

**Comment by Jason2866** [comment]
Closing since no issue with pioarduino
