### ISSUE TITLE
Error compiling project

### ISSUE THREAD

**Issue by Basoil** [pioarduino/platform-espressif32#34]
VSCode 1.93.1
PlatformIO core: 6.1.15, home: 3.4.4

Platformio.ini 
`[env:esp32s3wroom1]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3

...`

`Compiling .pio/build/esp32s3wroom1/libdf5/AsyncTCP/AsyncTCP.cpp.o
Compiling .pio/build/esp32s3wroom1/libbba/Network/NetworkClient.cpp.o
Compiling .pio/build/esp32s3wroom1/libbba/Network/NetworkEvents.cpp.o
Compiling .pio/build/esp32s3wroom1/libbba/Network/NetworkInterface.cpp.o
Compiling .pio/build/esp32s3wroom1/libbba/Network/NetworkManager.cpp.o
Compiling .pio/build/esp32s3wroom1/libbba/Network/NetworkServer.cpp.o
Compiling .pio/build/esp32s3wroom1/libbba/Network/NetworkUdp.cpp.o
Compiling .pio/build/esp32s3wroom1/lib791/NetworkClientSecure/NetworkClientSecure.cpp.o
Archiving .pio/build/esp32s3wroom1/libdf5/libAsyncTCP.a
Indexing .pio/build/esp32s3wroom1/libdf5/libAsyncTCP.a
Compiling .pio/build/esp32s3wroom1/lib791/NetworkClientSecure/ssl_client.cpp.o
Compiling .pio/build/esp32s3wroom1/lib1c7/AsyncTCP_SSL/tcp_mbedtls.c.o
In file included from .pio/libdeps/esp32s3wroom1/AsyncTCP_SSL/src/tcp_mbedtls.c:33:
.pio/libdeps/esp32s3wroom1/AsyncTCP_SSL/src/tcp_mbedtls.h:35:10: fatal error: mbedtls/net.h: No such file or directory
   35 | #include "mbedtls/net.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.`

with "platform=espressif32" (with old core 2.0.17) project compiled normally

**Comment by Jason2866** [comment]
See Arduino migration guide https://docs.espressif.com/projects/arduino-esp32/en/latest/migration_guides/2.x_to_3.0.html

**Comment by BlueAndi** [comment]
@Jason2866 But the mbedTLS is currently not part, right?

**Comment by Jason2866** [comment]
pioarduino uses orig. espressif Arduino release. So it is 100% same as espressif ArduinoIDE release.

**Comment by BlueAndi** [comment]
Ah ... its moved to framework-arduinoespressif32-libs ... original it was in the framework-arduinoespressif32/tools/sdk/...
