### ISSUE TITLE
Question about managed components (arduino as a component)

### ISSUE THREAD

**Issue by MikeSoperRubicon** [pioarduino/platform-espressif32#38]
Apologies for any ignorance on my part. When using arduino as a component of IDF, I noticed that when running full clean and build, the managed_components folder with all of the managed components automatically downloads itself. Is there any way to prevent this or  remove the dependencies of unwanted/unneeded conponents?

The project compiles perfectly fine, this is more a question about housekeeping and trimming unneeded components.

**Comment by Jason2866** [comment]
The managed components are forced to install from Arduino from this file https://github.com/espressif/arduino-esp32/blob/master/idf_component.yml without Arduino compile would fail.
