### ISSUE TITLE
3.1.0 RC2 Feedback

### ISSUE THREAD

**Issue by rac146** [pioarduino/platform-espressif32#45]
I gave the 3.1.0 RC2 a try and have some feedback, mostly around the Zigbee stuff..

I could not get this to build at all (ESP32C6) unless I had the `CONFIG_ZB_ENABLED` flag enabled in my sdkconfig. Not sure if this is intended or not.

Once I had `CONFIG_ZB_ENABLED` enabled, the build still failed - it looks like the managed_component version of `esp-zigbee-lib ` is different than what's expected from the Arduino library. In order to fix, I had to go grab this exact version of esp-zigbee-lib and manually put it in the components folder in my project:
https://github.com/espressif/esp-zigbee-sdk/tree/e8a4378bcef5468285b54f40f1b87b02e39f6e08

Once I had that, everything built correctly..

**Comment by Jason2866** [comment]
I see this too. Last CI build (with changes just in a boards manifest) do fail in zigbee part when Arduino is compiled as a component of IDF. Not a pioarduino issue. The problem will happen too when Arduino is used with native IDF. It is an issue in Arduino `idf_component.yml` not to pin the needed version.

**Comment by Jason2866** [comment]
ping @me-no-dev Arduino as component of IDF does fail in part zigbee

**Comment by P-R-O-C-H-Y** [comment]
@Jason2866 solved by https://github.com/espressif/esp32-arduino-lib-builder/pull/240 and other necessary changes are in this PR now https://github.com/espressif/arduino-esp32/pull/10566

**Comment by rac146** [comment]
Just tried RC3 - everything compiled first try!
