### ISSUE TITLE
Please make clear which compiler version is used.

### ISSUE THREAD

**Issue by xgnata** [pioarduino/platform-espressif32#47]
Pioarduino is great because gcc 8 toolchain is outdated.
The issue is that you offer several branches. It's not always clear which branch is more up to date than another. Looking at the commits count does not help.
Moreover it would be good to provide users with a gcc 13 toolchain. Maybe there is already a Pioarduino branch based on gcc 13 toolchain?

**Comment by Jason2866** [comment]
Look in the root directory in file [platform.json](https://github.com/pioarduino/platform-espressif32/blob/develop/platform.json) in the different branches to see what version is needed/used.
