### ISSUE TITLE
Where is the "Sponsor" button?

### ISSUE THREAD

**Issue by fredlcore** [pioarduino/platform-espressif32#48]
Thank you so much for this. This repo saves me a lot of work and I'd like to support it, but can't find the "Sponsor" button.

**Comment by Jason2866** [comment]
Thx a lot for the friendly words. Didn't think about a sponsor button. So you can't find one ;-)

**Comment by fredlcore** [comment]
If you happen to come up with one, let people know :)...
Anyway, rest assured that you are doing the community a great service!

**Comment by qniens** [comment]
Hi @Jason2866 , if you put up the _Buy me a coffee_ button  I'd be glad to treat you to one! 😊

**Comment by kylefmohr** [comment]
@Jason2866 That's very generous of you. We all greatly appreciate all of your hard work on this. Is there any charitable cause or organization you'd want people to support on your behalf?

**Comment by Jason2866** [comment]
@kylefmohr Well i am sure everyone knows an organization which is doing great.
So if you spend a little bit there, for honoring work people do for others i am happy, knowing that my work is maybe helping somewhere.

**Comment by Jason2866** [comment]
Thank you @kylefmohr for the idea. Changed the readme accordingly.
