### ISSUE TITLE
Compilation errros related to FS.h

### ISSUE THREAD

**Issue by IB-AST** [pioarduino/platform-espressif32#54]
Compilation stops with following error:
...libraries/FS/src/FS.h:49:17: error: expected '{' before ';' token

Function call _p() in FS.h expects two parameters, but just one is given:
  File(FileImplPtr p = FileImplPtr()) : _p(p) {
    _timeout = 0;
  }

Thanks a lot in advance for any hint or debug suggestions.

**Comment by Jason2866** [comment]
Please post your Platformio.ini  I don't know which branch or version you are using.

**Comment by IB-AST** [comment]
Thanks for your reply. I tried those two:

;platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip

platform = https://github.com/pioarduino/platform-espressif32.git#develop

**Comment by Jason2866** [comment]
CI examples do compile without any errors. There are examples which uses FS.
Check your code.

**Comment by IB-AST** [comment]
Thanks again, but I am not even using FS functionality. Looks like FS library gets involved when including ESP <WebServer.h>

**Comment by Jason2866** [comment]
Provide an minimal sketch where this happens. Without no help is possible

**Comment by Jason2866** [comment]
Closing since no feedback
