### ISSUE TITLE
version info not accepted by platformio

### ISSUE THREAD

**Issue by noweare1** [pioarduino/platform-espressif32#58]
To fix a platform to a project one can append @v.v.v  to the platform which represents the version of the platform.
pioarduino has a version of  "51.03.06+develop" which is not accepted by platformio . I get the error

Resolving esp32dev dependencies...
SemanticVersionError: Invalid simple block '51.03.06'

Right now the platform = espressif32  but I do not want to get that confused with the latest espressif  release of arduino core.

Thank you so much for this repo.

**Comment by Jason2866** [comment]
Can not implemented this way since the Platformio registry is not used and will not be used for the fork version.
