### ISSUE TITLE
Are the tests testing with the pioarduino platformio?

### ISSUE THREAD

**Issue by italocjs** [pioarduino/platform-espressif32#67]
Hi, i've been unable to run hello world and i noticed that Jason commented about CI in other issues, is the CI is running with the actual pioarduino as platform?.

here is hello world. https://github.com/pioarduino/platform-espressif32/blob/develop/examples/espidf-arduino-littlefs/platformio.ini

```

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino, espidf
board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv
monitor_speed = 115200

[env:esp32dev]
board = esp32dev
board_build.embed_txtfiles =
    managed_components/espressif__esp_insights/server_certs/https_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt

[env:esp32-c2-devkitm-1]
board = esp32-c2-devkitm-1

``` 

Maybe it needs to use `platform = https://github.com/pioarduino/platform-espressif32.git#develop` ?

**Comment by Jason2866** [comment]
Yes, you need to replace `platform = espressif32` from the examples with the version you want to use. This setting is used and usefull to use the already installed version (and only when one version is installed). So the best option for examples used for CI
