### ISSUE TITLE
Missing function WiFi._setStatus()?

### ISSUE THREAD

**Issue by flakmoppen** [pioarduino/platform-espressif32#71]
Firstly, I'm new to all this, so I might be completely wrong in posting this here, or to even expect this function to still work.

After starting to use this repo, `WiFi._setStatus()` no longer works, and VS Code complains that:
*class "WiFiClass" has no member "_setStatus"*

I'd love to not use this function, but unfortunately I need it because of [this issue](https://github.com/espressif/arduino-esp32/issues/7095).

Other than that, this has been awesome. I was missing some functionality that came with a newer version of idf, and using this repo solved those issues.
Thanks :)

**Comment by Jason2866** [comment]
Indeed wrong place. That's either a question or an issue in IDF, not caused from pioarduino.
May you ask here https://www.esp32.com/viewforum.php?f=2

**Comment by flakmoppen** [comment]
In that case I'm sorry for taking up your time.
And thanks for pointing me in the right direction.
