### ISSUE TITLE
captive portal examples don't work

### ISSUE THREAD

**Issue by BeaverUI** [pioarduino/platform-espressif32#78]
I've been trying to get the Captive Portal to work, but without success so far. I run a DNS server that redirects everything to the AP IP, and a webserver that responds to all requests with code 200 and some text. These both work fine; I can connect to the AP and browse to any random URL and get the message.

What would be required to get it to work, I believe, is an implementation of DHCP option 114 which allows setting a captive portal URL. At the moment I can't find any way to change the dhcps options when using the Arduino libs, since the esp_netifs are private to WiFiGeneric.cpp:

```
static esp_netif_t *esp_netifs[ESP_IF_MAX] = {NULL, NULL, NULL};

esp_netif_t *get_esp_interface_netif(esp_interface_t interface) {
  if (interface < ESP_IF_MAX) {
    return esp_netifs[interface];
  }
  return NULL;
}
```

You need the handle to the netif to change the dhcps options with ``esp_netif_dhcps_option()``.

**Comment by Jason2866** [comment]
Not an issues from build system.
