### ISSUE TITLE
ESP32-audioI2S  error

### ISSUE THREAD

**Issue by Yeharold** [pioarduino/platform-espressif32#79]
esphome/ESP32-audioI2S  lib get error

.pio/libdeps/esp32-s3-devkitm-1/ESP32-audioI2S/src/aac_decoder/aac_decoder.cpp: In function 'void UnpackQuads(int, int, int*)':
.pio/libdeps/esp32-s3-devkitm-1/ESP32-audioI2S/src/aac_decoder/aac_decoder.cpp:3289:106: error: invalid conversion from 'int*' to 'int32_t*' {aka 'long int*'} [-fpermissive]
 3289 |         nCodeBits = DecodeHuffmanScalar(huffTabSpec, &huffTabSpecInfo[cb - HUFFTAB_SPEC_OFFSET], bitBuf, &val);

**Comment by Jason2866** [comment]
Ask the esphome guys to update there used lib(s).
